# Generated by Django 4.2.3 on 2023-08-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0003_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table=None,
        ),
    ]
