# Generated by Django 4.2.3 on 2023-08-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0004_alter_books_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
